version: "3"
services:
  mongo:
    image: mongo:4.2
    ports:
      - "27017:27017"
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongo-data:/data/db
  api:
    image: aws-clone-server:0.0.2
    ports:
      - "3000:3000"

volumes:
  mongo-data:
