const initialWidgets = [
  {
    id: "irLnnOIu",
    title: "Recently visited",
    infoLink: true,
    footer: "View all services",
    big: true,
    isAdded: true,
  },
  {
    id: "mCsUr_BB",
    title: "Welcome to AWS",
    infoLink: false,
    footer: null,
    big: false,
    isAdded: true,
  },
  {
    id: "YJ93V_Wj",
    title: "AWS Health",
    infoLink: true,
    footer: "Go to AWS Health",
    big: false,
    isAdded: true,
  },
  {
    id: "VBqQM5zf",
    title: "Cost and usage",
    infoLink: true,
    footer: "Go to AWS Cost Management",
    big: true,
    isAdded: true,
  },
  {
    id: "RIyILDAp",
    title: "Build a solution",
    infoLink: true,
    footer: null,
    big: true,
    isAdded: true,
  },
  {
    id: "LCanROpO",
    title: "Trusted Advisor",
    infoLink: true,
    footer: "Go to Trusted Advisor",
    big: false,
    isAdded: true,
  },
  {
    id: "dXrePkX2",
    title: "Explore AWS",
    infoLink: true,
    footer: null,
    big: false,
    isAdded: true,
  },
  {
    id: "2APJvsb7",
    title: "Latest announcements",
    infoLink: true,
    footer: null,
    big: false,
    isAdded: true,
  },
  {
    id: "2BnJvsb6",
    title: "Recent AWS blog posts",
    infoLink: true,
    footer: null,
    big: false,
    isAdded: true,
  },
  {
    id: "fdXNnvZl",
    title: "Applications",
    infoLink: true,
    footer: "Go to Application Manager",
    big: true,
    isAdded: true,
  },
  {
    id: "WzeJcY2w",
    title: "Security Hub",
    infoLink: true,
    footer: "Go to Security Hub",
    big: false,
    isAdded: true,
  },
  {
    id: "3EwHwCXh",
    title: "Not Added 1",
    infoLink: true,
    footer: null,
    big: false,
    isAdded: false,
  },
  {
    id: "P5dCD5NV",
    title: "Not Added 2",
    infoLink: true,
    footer: null,
    big: false,
    isAdded: false,
  },
  {
    id: "yY4l_n-R",
    title: "Not Added 3",
    infoLink: true,
    footer: "Go to Application Manager",
    big: true,
    isAdded: false,
  },
  {
    id: "G8nLueuD",
    title: "Not Added 4",
    infoLink: true,
    footer: "Go to Security Hub",
    big: false,
    isAdded: false,
  },
];

const initialWidgetsv2 = [
  {
    id: "irLnnOIu",
    type: "recently-visited",
    size: "medium",
  },
  {
    id: "mCsUr_BB",
    type: "aws-welcome",
    size: "small",
  },
  {
    id: "YJ93V_Wj",
    type: "aws-health",
    size: "small",
  },
  {
    id: "VBqQM5zf",
    type: "const-and-usage",
    size: "medium",
  },
  {
    id: "RIyILDAp",
    type: "build-a-solution",
    size: "medium",
  },
  {
    id: "LCanROpO",
    type: "trusted-advisor",
    size: "small",
  },
  {
    id: "dXrePkX2",
    type: "explore-aws",
    size: "small",
  },
  {
    id: "2APJvsb7",
    type: "latest-announcements",
    size: "small",
  },
  {
    id: "2BnJvsb6",
    type: "recent-posts",
    size: "small",
  },
  {
    id: "fdXNnvZl",
    type: "applications",
    size: "medium",
  },
  {
    id: "WzeJcY2w",
    type: "security-hub",
    size: "small",
  },
];

module.exports = { initialWidgets, initialWidgetsv2 };
